# Setting Up Model Configration

model:
    name: 'magenta_rnn'
    checkpoint: 'https://storage.googleapis.com/magentadata/js/checkpoints/music_rnn/drum_kit_rnn'
    parameter:
        - temperature: 2.0 #need to think how to set range definition
        - steps: 32.0 #how mane steps
    function:
        - input: 'continueSequence the sequence'
